# core/integrations/joke_teller.py
# Auto-generated by Hermes Plugin Designer

from core.audit.audit_logger import AuditLogger
from core.audit.audit_event import AuditEvent
import random

class JokeTellerCapability:
    jokes = [
        "Why don't scientists trust atoms? Because they make up everything!",
        "What do you call fake spaghetti? An impasta!",
        "Why did the scarecrow win an award? Because he was outstanding in his field!",
        "What do you get when you cross a snowman and a vampire? Frostbite!",
        "Why did the math book look sad? Because it had too many problems."
    ]

    def __init__(self):
        self.audit = AuditLogger()

    def execute(self, *, action: str, query: str = "", **kwargs) -> str:
        try:
            if action == "tell_joke":
                joke = random.choice(self.jokes)
                self.audit.log(AuditEvent("JokeTold", f"User asked for a joke. Joke: {joke}"))
                return joke
            else:
                return "[ERROR] Unknown action: {}".format(action)
        except Exception as e:
            return "[ERROR] Failed to process action: {}".format(str(e))