# core/integrations/joke_teller.py
# Auto-generated by Hermes Plugin Designer

from core.audit.audit_logger import AuditLogger
from core.audit.audit_event import AuditEvent
import random

class JokeTellerCapability:
    def __init__(self):
        self.audit = AuditLogger()
        self.jokes = [
            "Why did the chicken cross the road? To get to the other side!",
            "What do you call fake spaghetti? An impasta!",
            "Why don't scientists trust atoms? Because they make up everything!",
            "How do you organize a space party? You planet!",
            "Why did the math book look sad? Because it had too many problems."
        ]
    
    def execute(self, *, action: str, query: str = "", **kwargs) -> str:
        try:
            if action == 'tell_joke':
                joke = random.choice(self.jokes)
                self.audit.log(AuditEvent(action=action, data={"query": query, "joke": joke}))
                return joke
            else:
                return "[ERROR] Unsupported action"
        except Exception as e:
            return f"[ERROR] {str(e)}"